server:
  port: 8080
  servlet:
    session:
      persistent: false
  tomcat:
    basedir: target/tomcat

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: identity-auth
              uri: ${identity-service.url:http://localhost:3000}
              predicates:
                - Path=/api/v1/identity/**
              filters:
                - StripPrefix=3
            - id: catalog-service
              uri: ${catalog-service.url:http://localhost:8081}
              predicates:
                - Path=/api/v1/catalog/**
              filters:
                - StripPrefix=3
            - id: media-service
              uri: ${media-service.url:http://localhost:3001}
              predicates:
                - Path=/api/v1/media/**
              filters:
                - RewritePath=/api/v1/media(?<remaining>/?.*), /api/uploadthing$\{remaining}
            - id: messaging-service
              uri: ${messaging-service.url:http://127.0.0.1:3002}
              predicates:
                - Path=/api/v1/messaging/**
              filters:
                - StripPrefix=3
