spring.application.name=marketplace-catalog
server.port=8081

spring.datasource.url=jdbc:postgresql://ep-curly-violet-ap01u03k-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_nJ5mTREBON9w&sslmode=require&channelBinding=require

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
    
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always